-- ============================================================
-- Dayflow HRMS — Seed Data
-- Demo credentials:
--   Admin:    admin@dayflow.com    / Admin@123
--   HR:       hr@dayflow.com       / Hr@123
--   Employees: employee@dayflow.com / Employee@123
--              alice@dayflow.com   / Employee@123
--              bob@dayflow.com     / Employee@123
-- ============================================================

-- Passwords are bcrypt hashes (12 rounds)
-- Admin@123   => $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewWnwTQ/K/RtTPZm (placeholder - will be generated by seed script)
-- Use the seed.ts script for proper hash generation.

-- ============================================================
-- DEPARTMENTS
-- ============================================================
INSERT INTO departments (id, name, description) VALUES
  ('11111111-1111-1111-1111-111111111111', 'Engineering', 'Software development and technical operations'),
  ('22222222-2222-2222-2222-222222222222', 'Human Resources', 'People operations and talent management'),
  ('33333333-3333-3333-3333-333333333333', 'Finance', 'Financial planning, accounting, and payroll'),
  ('44444444-4444-4444-4444-444444444444', 'Marketing', 'Brand, campaigns, and growth'),
  ('55555555-5555-5555-5555-555555555555', 'Operations', 'Business operations and logistics');

-- ============================================================
-- NOTE: Run seed.ts instead of this file directly.
-- seed.ts will properly hash passwords and insert all data.
-- This file is a reference only.
-- ============================================================
